export const LOAN_ROUTER_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "collateralLiquidator_", type: "address", internalType: "address" },
      { name: "collateralWrapper_", type: "address", internalType: "address" },
      { name: "depositTimelock_", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "IMPLEMENTATION_VERSION",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "borrow",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
      {
        name: "lenderDepositInfos",
        type: "tuple[]",
        internalType: "struct ILoanRouter.LenderDepositInfo[]",
        components: [
          { name: "depositType", type: "uint8", internalType: "enum ILoanRouter.DepositType" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1", internalType: "bytes1" },
      { name: "name", type: "string", internalType: "string" },
      { name: "version", type: "string", internalType: "string" },
      { name: "chainId", type: "uint256", internalType: "uint256" },
      { name: "verifyingContract", type: "address", internalType: "address" },
      { name: "salt", type: "bytes32", internalType: "bytes32" },
      { name: "extensions", type: "uint256[]", internalType: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getApproved",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoleAdmin",
    inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "increaseNonce",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "admin", type: "address", internalType: "address" },
      { name: "feeRecipient", type: "address", internalType: "address" },
      { name: "liquidationFeeRate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isApprovedForAll",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "operator", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lendingPositionInfo",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "loanTermsHash_", type: "bytes32", internalType: "bytes32" },
      { name: "trancheIndex", type: "uint8", internalType: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidate",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "loanState",
    inputs: [{ name: "loanTermsHash_", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "status", type: "uint8", internalType: "enum ILoanRouter.LoanStatus" },
      { name: "maturity", type: "uint64", internalType: "uint64" },
      { name: "repaymentDeadline", type: "uint64", internalType: "uint64" },
      { name: "scaledBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "loanState",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "status", type: "uint8", internalType: "enum ILoanRouter.LoanStatus" },
      { name: "maturity", type: "uint64", internalType: "uint64" },
      { name: "repaymentDeadline", type: "uint64", internalType: "uint64" },
      { name: "scaledBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "loanTermsHash",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "loanTokenIds",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "multicall",
    inputs: [{ name: "data", type: "bytes[]", internalType: "bytes[]" }],
    outputs: [{ name: "results", type: "bytes[]", internalType: "bytes[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onCollateralLiquidated",
    inputs: [
      { name: "encodedLoanTerms", type: "bytes", internalType: "bytes" },
      { name: "proceeds", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ownerOf",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paused",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quote",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "timestamp", type: "uint64", internalType: "uint64" },
    ],
    outputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quote",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "callerConfirmation", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repay",
    inputs: [
      {
        name: "loanTerms",
        type: "tuple",
        internalType: "struct ILoanRouter.LoanTerms",
        components: [
          { name: "expiration", type: "uint64", internalType: "uint64" },
          { name: "borrower", type: "address", internalType: "address" },
          { name: "currencyToken", type: "address", internalType: "address" },
          { name: "collateralToken", type: "address", internalType: "address" },
          { name: "collateralTokenId", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint64", internalType: "uint64" },
          { name: "repaymentInterval", type: "uint64", internalType: "uint64" },
          { name: "interestRateModel", type: "address", internalType: "address" },
          { name: "gracePeriodRate", type: "uint256", internalType: "uint256" },
          { name: "gracePeriodDuration", type: "uint256", internalType: "uint256" },
          {
            name: "feeSpec",
            type: "tuple",
            internalType: "struct ILoanRouter.FeeSpec",
            components: [
              { name: "originationFee", type: "uint256", internalType: "uint256" },
              { name: "exitFee", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "trancheSpecs",
            type: "tuple[]",
            internalType: "struct ILoanRouter.TrancheSpec[]",
            components: [
              { name: "lender", type: "address", internalType: "address" },
              { name: "amount", type: "uint256", internalType: "uint256" },
              { name: "rate", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "collateralWrapperContext", type: "bytes", internalType: "bytes" },
          { name: "options", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "safeTransferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "safeTransferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setApprovalForAll",
    inputs: [
      { name: "operator", type: "address", internalType: "address" },
      { name: "approved", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeRecipient",
    inputs: [{ name: "recipient", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLiquidationFeeRate",
    inputs: [{ name: "liquidationFeeRate", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenByIndex",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenOfOwnerByIndex",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "index", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenURI",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawERC20",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "approved", type: "address", indexed: true, internalType: "address" },
      { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ApprovalForAll",
    inputs: [
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "operator", type: "address", indexed: true, internalType: "address" },
      { name: "approved", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  { type: "event", name: "EIP712DomainChanged", inputs: [], anonymous: false },
  {
    type: "event",
    name: "ERC20Withdrawn",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeRecipientSet",
    inputs: [{ name: "recipient", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "HookFailed",
    inputs: [{ name: "reason", type: "string", indexed: false, internalType: "string" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [{ name: "version", type: "uint64", indexed: false, internalType: "uint64" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "LenderLiquidationRepaid",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "lender", type: "address", indexed: true, internalType: "address" },
      { name: "trancheIndex", type: "uint8", indexed: true, internalType: "uint8" },
      { name: "principal", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "interest", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LenderPositionMinted",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "lender", type: "address", indexed: true, internalType: "address" },
      { name: "trancheIndex", type: "uint8", indexed: true, internalType: "uint8" },
      { name: "tokenId", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LenderRepaid",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "lender", type: "address", indexed: true, internalType: "address" },
      { name: "trancheIndex", type: "uint8", indexed: true, internalType: "uint8" },
      { name: "principal", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "interest", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "prepay", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LiquidationFeeRateSet",
    inputs: [{ name: "liquidationFeeRate", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanCollateralLiquidated",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "proceeds", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "liquidationFee", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "surplus", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanLiquidated",
    inputs: [{ name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanOriginated",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "borrower", type: "address", indexed: true, internalType: "address" },
      { name: "currencyToken", type: "address", indexed: true, internalType: "address" },
      { name: "principal", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "originationFee", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanRepaid",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "borrower", type: "address", indexed: true, internalType: "address" },
      { name: "principal", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "interest", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "prepayment", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "exitFee", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "isRepaid", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NonceIncreased",
    inputs: [
      { name: "loanTermsHash", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "lender", type: "address", indexed: true, internalType: "address" },
      { name: "nonce", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Paused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "previousAdminRole", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "newAdminRole", type: "bytes32", indexed: true, internalType: "bytes32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "sender", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "account", type: "address", indexed: true, internalType: "address" },
      { name: "sender", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "tokenId", type: "uint256", indexed: true, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TransferFailed",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "intendedRecipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unpaused",
    inputs: [{ name: "account", type: "address", indexed: false, internalType: "address" }],
    anonymous: false,
  },
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "neededRole", type: "bytes32", internalType: "bytes32" },
    ],
  },
  { type: "error", name: "AddressEmptyCode", inputs: [{ name: "target", type: "address", internalType: "address" }] },
  { type: "error", name: "ECDSAInvalidSignature", inputs: [] },
  {
    type: "error",
    name: "ECDSAInvalidSignatureLength",
    inputs: [{ name: "length", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignatureS",
    inputs: [{ name: "s", type: "bytes32", internalType: "bytes32" }],
  },
  { type: "error", name: "ERC721EnumerableForbiddenBatchMint", inputs: [] },
  {
    type: "error",
    name: "ERC721IncorrectOwner",
    inputs: [
      { name: "sender", type: "address", internalType: "address" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
      { name: "owner", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "ERC721InsufficientApproval",
    inputs: [
      { name: "operator", type: "address", internalType: "address" },
      { name: "tokenId", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC721InvalidApprover",
    inputs: [{ name: "approver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC721InvalidOperator",
    inputs: [{ name: "operator", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC721InvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC721InvalidReceiver",
    inputs: [{ name: "receiver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC721InvalidSender",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC721NonexistentToken",
    inputs: [{ name: "tokenId", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "ERC721OutOfBoundsIndex",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "index", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "EnforcedPause", inputs: [] },
  { type: "error", name: "ExpectedPause", inputs: [] },
  { type: "error", name: "FailedCall", inputs: [] },
  { type: "error", name: "InvalidAddress", inputs: [] },
  { type: "error", name: "InvalidAmount", inputs: [] },
  { type: "error", name: "InvalidCaller", inputs: [] },
  { type: "error", name: "InvalidDepositType", inputs: [] },
  { type: "error", name: "InvalidInitialization", inputs: [] },
  { type: "error", name: "InvalidLength", inputs: [] },
  { type: "error", name: "InvalidLoanState", inputs: [] },
  { type: "error", name: "InvalidLoanTerms", inputs: [{ name: "reason", type: "string", internalType: "string" }] },
  { type: "error", name: "InvalidSignature", inputs: [] },
  { type: "error", name: "NotInitializing", inputs: [] },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
] as const;
