/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bust-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ApiV2Controller_bustCache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApiV2Controller_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/borrow/application/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApplicationController_getAdmins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/borrow/application/update-constants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ApplicationController_"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/borrow/application/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ApplicationController_getApplicationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/borrow/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ApplicationController_createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/borrow/application/task/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["ApplicationController_updateTaskStatus"];
        trace?: never;
    };
    "/ms-app/depin/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepinController_getDepinQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ms-app/yieldpass/metrics/{chainId}/{marketId}/{account}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["YieldpassController_getYieldpassMarketAccountMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/testnet/whitelisted-eids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsdaiController_getWhitelistedEids[0]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/whitelisted-eids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsdaiController_getWhitelistedEids[1]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallet/takeSnapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_takeSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallet/integrations-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getWalletIntegrationsData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallet/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallet/adjusted-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getAdjustedRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallet/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallets/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletsController_getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallets/alignment-leaderboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletsController_getAlignmentLeaderboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallets/referral-leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletsController_getReferralLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/wallets/totalWallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletsController_getTotalWallets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/invite/available/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InviteController_available"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/testnet/tvl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getTvl[0]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/tvl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getTvl[1]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/apy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getApy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/current-apy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getUtilization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/reset-tvl-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_resetTvlHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/reset-utilization-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_resetUtilizationHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/reset-susdai-fmv-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DashboardController_resetSusdaiFmvHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/reset-usdai-price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DashboardController_resetUsdaiPriceHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/proof-of-reserves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getProofOfReserves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/reserve-ratio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_getReserveRatio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard/expected-apy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DashboardController_"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/usdai-supply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getUSDaiSupply"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/susdai-supply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getsUSDaiSupply"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/susai-staking-apy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getSusaiStakingApy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/susdai-utilization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getSusdaiUtilization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/protocol-alignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getProtocolAlignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/total-allo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getTotalAllo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/raw-integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/raw-xp-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getXpState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/accounts-totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getAccountsTotals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/public/integration-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_getIntegrationSummaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/external/v1/reserves-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get reserves summary
         * @description Returns aggregated protocol metrics including staking APY, reserves breakdown, and loan details
         */
        get: operations["ExternalController_getReservesSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/metadata/testnet/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetadataController_getRWACollectionMetadata[0]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/metadata/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetadataController_getRWACollectionMetadata[1]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/metadata/testnet/{version}/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetadataController_getRWATokenMetadata[0]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/metadata/{version}/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetadataController_getRWATokenMetadata[1]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/metadata/testnet/{version}/{tokenIdRange}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetadataController_getRWATokenMetadataPSA[0]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/metadata/{version}/{tokenIdRange}/{file}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetadataController_getRWATokenMetadataPSA[1]"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuoteController_getRWAQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usdai/borrow/rwa/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["QuoteController_getRWAQuotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet-screening/{walletAddress}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletScreeningController_screenWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GetAdminsDto: {
            admins: string[];
        };
        GetApplicationDto: {
            /** @description Application ID */
            id: number;
            /** @description Application creation timestamp */
            created_at: string;
            /** @description Steps associated with the application */
            Step: {
                /** @description Step ID */
                id: string;
                /** @description Step identifier */
                step_id: string;
                /** @description Application ID */
                application_id: number;
                /** @description Step creation timestamp */
                created_at: string;
                /** @description Task IDs */
                tasks: string[];
                /** @description Tasks for this step */
                Task: {
                    /** @description Task ID */
                    id: string;
                    /** @description Task identifier */
                    task_id: string;
                    /** @description Step ID */
                    step_id: string;
                    /** @description Application ID */
                    application_id: number;
                    /**
                     * @description Task status
                     * @enum {string|null}
                     */
                    status: "PENDING" | "TODO" | "COMPLETED" | "UNAVAILABLE" | null;
                    /** @description Task creation timestamp */
                    created_at: string;
                }[] | null;
            }[] | null;
        };
        UpdateTaskStatusDto: {
            /** @description Application ID */
            application_id: number;
            /**
             * @description Step ID
             * @enum {string}
             */
            step_id: "borrower-intake" | "due-diligence" | "spv-formation" | "purchase-order" | "equipment-delivery" | "funding";
            /**
             * @description Task ID
             * @enum {string}
             */
            task_id: "user-application" | "execute-nda" | "intake-call" | "executed-term-sheet" | "kyb-aml" | "colocation-agreement" | "data-center-one-pager" | "offtake-agreement" | "purchase-order-oem" | "customer-service-agreement" | "bridge-loan-onboarding" | "proof-of-order-placement" | "loan-proceeds-in-escrow" | "executed-sale-contribution-agreement" | "install-aravolta-monitoring" | "executed-warehouse-receipt" | "chips-added-to-master-insurance-policy" | "assets-tokenized" | "loan-executed" | "onramp-offramp" | "country-legal-review" | "spv-llc-formation" | "executed-spv-llc-documents";
            /**
             * @description Task status
             * @enum {string|null}
             */
            status: "PENDING" | "TODO" | "COMPLETED" | "UNAVAILABLE" | "SKIPPED" | "REJECTED" | null;
        };
        QuoteResponseDto: {
            quote: {
                token: string;
                /** Format: int64 */
                tokenId: number;
                currency: string;
                /** Format: int64 */
                price: number;
                /** Format: int64 */
                duration: number;
                /** Format: int64 */
                timestamp: number;
            };
            signature: string;
        };
        YieldpassMarketAccountMetricsResponseDto: {
            nodesDeposited: number;
            ypBalanceIncLp: number;
            tokensBorrowed: number;
        };
        GetWhitelistedEidsResponseDto: {
            [key: string]: {
                [key: string]: boolean;
            };
        };
        GetIntegrationsDataDto: {
            [key: string]: {
                type: "ERC20" | "LP_ERC20" | "VAULT" | "MORPHO_MARKET";
                balance: number | null;
                tvl: number | null;
                apy: number | null;
                usdPrice: number | null;
            };
        };
        GetRatesDto: {
            [key: string]: number;
        };
        GetWalletDto: {
            /** @description Wallet data */
            wallet: {
                /** @description Wallet address */
                address: string;
                /** @description Invite used */
                inviteUsed: {
                    /** @description Invite code */
                    code: string;
                    /** @description Invite owner */
                    owner: string | null;
                    /** @description Invite percentage */
                    percentage: number;
                } | null;
                /** @description Wallet invite */
                invite: {
                    /** @description Invite code */
                    code: string;
                    /** @description Invite percentage */
                    percentage: number;
                };
                team: {
                    /** @description Team member address */
                    address: string;
                    /** @description Team member XP */
                    xp: number;
                    /**
                     * @description Team member alignment
                     * @enum {string|null}
                     */
                    alignment: "ICO" | "Airdrop" | null;
                }[];
                /** @description KYC verified */
                isKycVerified: boolean;
            } | null;
            /** @description XP state */
            xpState: {
                xp: {
                    [key: string]: number;
                };
                /** @description Total XP */
                totalXp: number;
                /** @description ICO XP */
                icoXp: number;
                /** @description Airdrop XP */
                airdropXp: number;
                /** @description No alignment XP */
                noAlignmentXp: number;
                /** @description Invite XP */
                inviteXp: number;
                /** @description Wallet rank */
                rank: number;
                /** @description Qualified wallets */
                qualifiedWallets: number;
                /**
                 * @description Wallet alignment
                 * @enum {string|null}
                 */
                alignment: "ICO" | "Airdrop" | null;
                /** @description Wallet alignment percentage */
                alignmentPercentage: number;
            } | null;
        };
        GetLeaderboardDto: {
            address: string;
            xp: number;
            qualifiedMembers: number;
            rank: number;
            invitedBy: string | null;
            /** @enum {string|null} */
            alignment: "ICO" | "Airdrop" | null;
        }[];
        GetAlignmentLeaderboardsDto: {
            ICO: {
                leaderboard: {
                    address: string;
                    xp: number;
                }[];
                count: number;
                totalXp: number;
            };
            Airdrop: {
                leaderboard: {
                    address: string;
                    xp: number;
                }[];
                count: number;
                totalXp: number;
            };
        };
        GetReferralLeaderboardDto: {
            rank: number;
            address: string;
            qualifiedWallets: number;
        }[][];
        GetTotalWalletsDto: {
            totalWallets: number;
        };
        LoginRequestBodyDto: {
            /** @description Invite code used in case of signup */
            inviteCode?: string;
        };
        IsCodeAvailableResponseDto: {
            isAvailable: boolean;
            percentage: number;
        };
        TvlResponseDto: {
            /** @description TVL value in USD */
            tvl: number;
            /** @description Deposit cap */
            cap: number;
            /** @description Deposit cap counter */
            counter: number;
            /** @description USDAI TVL */
            usdaiTvl: number;
            /** @description sUSD TVL */
            sUsdaiTvl: number;
        };
        GetApyResponseDto: {
            result: number;
        };
        UtilizationResponseDto: {
            result: number;
        };
        ProofOfReservesResponseDto: ({
            /** @enum {string} */
            type: "LEGACY_DEAL";
            documentId: string;
            name: string;
            chain: number;
            borrower: string | null;
            stage: number;
            locationName: string;
            locationLongitude: number;
            locationLatitude: number;
            amount: string;
            term: number;
            apr: number;
            share?: number;
            offTake: (number) | null;
            pool: string;
        } | {
            /** @enum {string} */
            type: "TBILL";
            name: string;
            chain: number;
            icon: string;
            iconUrl: string;
            reserveLink: string;
            apy: number;
            amount: string;
            share: number;
        } | {
            /** @enum {string} */
            type: "DEAL";
            documentId: string;
            name: string;
            chain: number;
            borrower: string | null;
            stage: number;
            locationName: string;
            locationLongitude: number;
            locationLatitude: number;
            amount: string;
            term: number;
            apr: number;
            share?: number;
            offTake: (number) | null;
        })[];
        GetReserveRatioResponseDto: {
            result: string;
        };
        ExpectedApyResponseDto: {
            result: {
                projectedApy: number;
                detailedDeals: {
                    /** @enum {string} */
                    type: "DEAL";
                    documentId: string;
                    name: string;
                    chain: number;
                    borrower: string | null;
                    stage: number;
                    locationName: string;
                    locationLongitude: number;
                    locationLatitude: number;
                    amount: string;
                    term: number;
                    apr: number;
                    share?: number;
                    offTake: (number) | null;
                    dealYield: number;
                    contributionToApy: number;
                }[];
            } | null;
        };
        DashboardResponseDto: {
            tvlHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            usdaiTvlHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            sUsdaiTvlHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            apyHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            utilizationHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            mintedUsdaiHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            stakedUsdaiHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            susdaiFmvHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
            usdaiPriceHistory: {
                /** Format: date-time */
                timestamp: string;
                value: string;
            }[];
        };
        SusdaiUtilizationResponseDto: {
            utilization: number | null;
            expectedUtilization: number | null;
        };
        ProtocolAlignmentsResponseDto: {
            usdai_alignment: number;
            susdai_alignment: number;
        };
        TotalAlloResponseDto: {
            total: number;
        };
        ReservesSummaryResponseDto: {
            staking_apy: number;
            staking_ratio: number;
            total_reserves: number;
            cash_reserves: number;
            loans_reserves: number;
            active_loans: {
                loan_id: string;
                asset_name: string;
                amount: number;
                term: number;
                apr: number;
                insurance: number | null;
            }[];
            upcoming_loans: {
                loan_id: string;
                asset_name: string;
                amount: number;
                term: number;
                apr: number;
                insurance: number | null;
            }[];
            metadata: {
                timestamp: string;
                cached: boolean;
            };
        };
        GetRWAQuoteResponseDto: {
            quote: {
                token: string;
                /** Format: int64 */
                startTokenId: number;
                /** Format: int64 */
                endTokenId: number;
                currency: string;
                /** Format: int64 */
                price: number;
                /** Format: int64 */
                timestamp: number;
                /** Format: int64 */
                duration: number;
            };
            signature: string;
            prices: {
                currentPrice: number;
                maturityPrice: number;
                originalPrice: number;
            }[];
        };
        GetRwaQuotesBodyDto: {
            startTokenId: number | string;
            endTokenId: number | string;
            collectionId: string;
            currencyId: string;
            chainId: number;
        }[];
        GetRWAQuotesResponseDto: {
            quote: {
                token: string;
                /** Format: int64 */
                startTokenId: number;
                /** Format: int64 */
                endTokenId: number;
                currency: string;
                /** Format: int64 */
                price: number;
                /** Format: int64 */
                timestamp: number;
                /** Format: int64 */
                duration: number;
            };
            signature: string;
            prices: {
                currentPrice: number;
                maturityPrice: number;
                originalPrice: number;
            }[];
        }[];
        WalletRiskResponseDto: {
            /**
             * @description Whether the wallet address is considered risky based on TRM Labs screening (risk score >= 15)
             * @example false
             */
            isRisky: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ApiV2Controller_bustCache: {
        parameters: {
            query: {
                key: string;
                params: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApiV2Controller_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationController_getAdmins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAdminsDto"];
                };
            };
        };
    };
    ApplicationController_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationController_getApplicationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application with steps and tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApplicationDto"];
                };
            };
        };
    };
    ApplicationController_createApplication: {
        parameters: {
            query: {
                /** @description Application ID to create */
                applicationId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application created with steps and tasks */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApplicationDto"];
                };
            };
        };
    };
    ApplicationController_updateTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Task status update request */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskStatusDto"];
            };
        };
        responses: {
            /** @description Task status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepinController_getDepinQuote: {
        parameters: {
            query: {
                /** @description Token ID of the GPU */
                tokenId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token price signed quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        /** @example Bad Request */
                        message: string;
                        /** @example Bad Request */
                        error?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        statusCode: number;
                        /** @example Internal Server Error */
                        message: string;
                        /** @example Internal Server Error */
                        error?: string;
                    };
                };
            };
        };
    };
    YieldpassController_getYieldpassMarketAccountMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chainId: string;
                marketId: string;
                account: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yieldpass market account metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YieldpassMarketAccountMetricsResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        /** @example Bad Request */
                        message: string;
                        /** @example Bad Request */
                        error?: string;
                    };
                };
            };
        };
    };
    "UsdaiController_getWhitelistedEids[0]": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whitelisted EIDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "1": {
                     *         "1": true,
                     *         "2": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GetWhitelistedEidsResponseDto"];
                };
            };
        };
    };
    "UsdaiController_getWhitelistedEids[1]": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whitelisted EIDs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "1": {
                     *         "1": true,
                     *         "2": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["GetWhitelistedEidsResponseDto"];
                };
            };
        };
    };
    WalletController_takeSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WalletController_getWalletIntegrationsData: {
        parameters: {
            query: {
                /** @description Wallet address */
                address?: string;
                chainId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet integrations data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIntegrationsDataDto"];
                };
            };
        };
    };
    WalletController_getRates: {
        parameters: {
            query?: {
                /** @description Wallet address */
                address?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRatesDto"];
                };
            };
        };
    };
    WalletController_getAdjustedRates: {
        parameters: {
            query?: {
                /** @description Wallet address */
                address?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRatesDto"];
                };
            };
        };
    };
    WalletController_: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wallet address */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetWalletDto"];
                };
            };
        };
    };
    WalletsController_getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLeaderboardDto"];
                };
            };
        };
    };
    WalletsController_getAlignmentLeaderboards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alignment leaderboards */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAlignmentLeaderboardsDto"];
                };
            };
        };
    };
    WalletsController_getReferralLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Referral leaderboard info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetReferralLeaderboardDto"];
                };
            };
        };
    };
    WalletsController_getTotalWallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Total wallets info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTotalWalletsDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header: {
                /** @description Privy ID token */
                "privy-id-token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestBodyDto"];
            };
        };
        responses: {
            /** @description User logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InviteController_available: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsCodeAvailableResponseDto"];
                };
            };
        };
    };
    "DashboardController_getTvl[0]": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current TVL value from USDai and sUSDai contracts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TvlResponseDto"];
                };
            };
        };
    };
    "DashboardController_getTvl[1]": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current TVL value from USDai and sUSDai contracts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TvlResponseDto"];
                };
            };
        };
    };
    DashboardController_getApy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Last stored APY value. is stored as a 18 Decimals value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApyResponseDto"];
                };
            };
        };
    };
    DashboardController_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Last stored APY value. is stored as a 18 Decimals value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApyResponseDto"];
                };
            };
        };
    };
    DashboardController_getUtilization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ration of staked usdai */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtilizationResponseDto"];
                };
            };
        };
    };
    DashboardController_resetTvlHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_resetUtilizationHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_resetSusdaiFmvHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_resetUsdaiPriceHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getProofOfReserves: {
        parameters: {
            query: {
                chainId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proof of reserves data showing the backing assets for USDai, including their APY, amount, and share. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofOfReservesResponseDto"];
                };
            };
        };
    };
    DashboardController_getReserveRatio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns instantly calculated reserve ratio. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetReserveRatioResponseDto"];
                };
            };
        };
    };
    DashboardController_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expected APY data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpectedApyResponseDto"];
                };
            };
        };
    };
    DashboardController_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comprehensive dashboard data including TVL, APY, utilization and their historical values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
        };
    };
    PublicController_getUSDaiSupply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_getsUSDaiSupply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_getSusaiStakingApy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_getSusdaiUtilization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Susdai Utilization value as a number (percentage) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SusdaiUtilizationResponseDto"];
                };
            };
        };
    };
    PublicController_getProtocolAlignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Protocol total alignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolAlignmentsResponseDto"];
                };
            };
        };
    };
    PublicController_getTotalAllo: {
        parameters: {
            query?: {
                /** @description Partner */
                partner?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Total Allo in the protocol */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotalAlloResponseDto"];
                };
            };
        };
    };
    PublicController_getIntegrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_getXpState: {
        parameters: {
            query: {
                account: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_getAccountsTotals: {
        parameters: {
            query: {
                cursor: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_getIntegrationSummaries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalController_getReservesSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reserves summary with staking metrics, reserves breakdown, and loan details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservesSummaryResponseDto"];
                };
            };
        };
    };
    "MetadataController_getRWACollectionMetadata[0]": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "MetadataController_getRWACollectionMetadata[1]": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "MetadataController_getRWATokenMetadata[0]": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "MetadataController_getRWATokenMetadata[1]": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "MetadataController_getRWATokenMetadataPSA[0]": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenIdRange: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "MetadataController_getRWATokenMetadataPSA[1]": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenIdRange: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuoteController_getRWAQuote: {
        parameters: {
            query: {
                /** @description Start Token ID */
                startTokenId: string;
                /** @description End Token ID */
                endTokenId: string;
                /** @description Chain ID */
                chainId: number;
                /** @description Collection ID */
                collectionId: string;
                /** @description Currency ID */
                currencyId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token price signed quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRWAQuoteResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        /** @example Bad Request */
                        message: string;
                        /** @example Bad Request */
                        error?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        statusCode: number;
                        /** @example Internal Server Error */
                        message: string;
                        /** @example Internal Server Error */
                        error?: string;
                    };
                };
            };
        };
    };
    QuoteController_getRWAQuotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetRwaQuotesBodyDto"];
            };
        };
        responses: {
            /** @description Token price signed quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRWAQuotesResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 400 */
                        statusCode: number;
                        /** @example Bad Request */
                        message: string;
                        /** @example Bad Request */
                        error?: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 500 */
                        statusCode: number;
                        /** @example Internal Server Error */
                        message: string;
                        /** @example Internal Server Error */
                        error?: string;
                    };
                };
            };
        };
    };
    WalletScreeningController_screenWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The wallet address to screen for risk */
                walletAddress: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk assessment for the wallet address. Uses TRM Labs screening with 30-day cache. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRiskResponseDto"];
                };
            };
        };
    };
}
